#!/bin/bash

# This will attempt to reinstall all packages with missing files.
# Note that this can brick your system but may be able to also fix it other times

pacman -Qk 2>/dev/null | grep -v ' 0 missing files' | cut -d: -f1 |
    while read -r package; do
      echo "Reading package ..."  
      sudo pacman -S "$package" --overwrite "*" --noconfirm
    done

echo "Done reinstalling packages"
exit 0