#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &

# dex: https://github.com/jceb/dex (generate and execute DesktopEntry files)
dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &

# Timeout, so apps show in tray
sleep 3s;

# insync start &
nohup nextcloud &>/dev/null
#Communication
# whatsapp-natifier &
# signal &
# telegram-desktop &
# discord &
 nohup steam -pipewire -pipewire-dmabuf &>/dev/null
 nohup keepassxc &>/def/null
 nm-applet --indicator # network tray icon
