#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &

# dex: https://github.com/jceb/dex (generate and execute DesktopEntry files)
dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &

# Timeout, so apps show in tray
sleep 3s;

if [[ "$(lsusb | grep 'WLAN Adapter (Driver CDROM Mode)')" == "" ]] ; then
	usb_modeswitch -KW -v $(lsusb | grep "WLAN Adapter (Driver CDROM Mode)" | awk '{ print $6}' | sed 's/:..../ /g') -p $(lsusb | grep "WLAN Adapter (Driver CDROM Mode)" | awk '{ print $6}' | sed 's/....:/ /g') ;
fi

#nohup nm-applet --indicator &>/dev/null
#nohup openrgb --startminimized &>/dev/null
#
#nohup nextcloud &>/dev/null
#nohup keepassxc &>/dev/null
#
#nohup steam &>/dev/null # -pipewire -pipewire-dmabuf
#nohup telegram-desktop &>/dev/null
#nohup discord &>/dev/null

# XDG_CURRENT_DESKTOP=wayland flameshot

notify-send "Startup completed"
