#!/bin/bash
#
# This scrip will attempt to upgrade packages using the arch package manager.
# Note: In non interactive mode this will only request an upgrade after
#       a certain threshold is reached.
#       In an interactive (tty) session the threshold is automatically ignored.

which checkupdates > /dev/null || sudo pacman -S pacman-contrib;

old_dir="$(dir)"
out_of_date_packs=$(checkupdates | wc -l)
OUTDATED_ALLOWED=50

# Verify yay is installed else install yay
if [ ! -f "$(which yay 2>/dev/null)" ]; then
  which git > /dev/null || pacman -S git base-devel
  git clone https://aur.archlinux.org/yay.git yay-setup &&\
  cd yay-setup &&\
  makepkg -si &&\
  cd "$old_dir" &&\
  rm -rf yay-setup
fi

# Only update if >= X packages are out of date (idea: stabe system intervalls)
if [[ $out_of_date_packs -ge $OUTDATED_ALLOWED ]] || [[ "$(tty)" =~ "not a tty" ]]; then
  kitty --hold --name "Auto_Update" --title "Auto_Update" sh -c \
   "echo 'Requesting System upgrade ($out_of_date_packs packages)'; yay -Syu --noconfirm; exit_code=$?; read -n 1 -s -p 'Press [ANY] key to continue ...' dummy;exit $exit_code"
  [ $(checkupdates | wc -l) -eq 0 ] && echo "Auto Update Success" || (echo "Auto Update Failed")
else
  msg="Less than $OUTDATED_ALLOWED packages outdated => skipping update"
  if [[ "$(tty)" =~ "not a tty" ]]; then
    notify-send "$msg"
  else
    echo "$msg"
  fi
fi

pkill -RTMIN+8 waybar >/dev/null 2>/dev/null # Update waybar displayed packages

exit 0
