#!/usr/bin/env sh
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "${HYPRGAMEMODE,,}" == 'true' ] ; then
    #hyprctl eval 'hl.config({ animations = { enabled = false } })'
   hyprctl eval 'hl.config({
      animations = {
        enabled = false,
      },
      decoration = {
        shadow = { enabled = false },
        blur = { enabled = false },
        active_opacity =  1,
        inactive_opacity =  1,
        fullscreen_opacity =  1,
        rounding = 0,
      },
      general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 1
      }
    });
    hl.animation({ leaf = "borderangle", enabled = false})'
    hyprctl hyprsunset temperature identitiy # remove blue light filter
    hyprctl notify 1 5000 "rgb(ff1ea3)" "Gamemode [ON]"
   #killall waybar
    exit 0
else
    hyprctl notify 1 5000 "rgb(ff1ea3)" "Gamemode [OFF]"
    hyprctl eval 'hl.config({
      animations = {
        enabled = true,
      },});'
    hyprctl reload
    [ ! -z "$(ps -x | awk 'match($5,/waybar/) {print $5}')" ] || (nohup waybar >/dev/null 2>/dev/null & disown %)
    exit 0
fi
exit 1

