#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Catppuccin-Mocha-Standard-Lavender-Dark'
    # 'Arc-Dark'
    #get avalable themes with 'ls /usr/share/themes'
ICONS='a-candy-beauty-icon-theme'
    # 'a-candy-beauty-icon-theme'
FONT='Inter 11'
    # 'Noto Sans 11'
CURSOR='Catppuccin-Lavender-Cursors'
    # 'Bibata-Modern-Ice'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
