#!/bin/sh

#kitty -e vim +50 "~/.config/hypr/hyprland-keybinds.conf"
#kitty -e vim "~/.config/hypr/cheatsheet.md"
kitty sh -c 'vim - | grep -n "bind.*=" ~/.config/hypr/hyprland-keybinds.conf | grep -v "#bind"' # cat "~/.config/hypr/hyprland-keybinds.conf" > grep -E "bind.*=" > grep -v "#bind" > nohup vim - 2>&1
