#!/bin/bash

case "$(hyprctl activewindow -j | jq -r ".class")" in
  "steam"|"Microsoft Teams - Preview")
  # Close window to tray
  notify-send "Minimizing App - $(hyprctl activewindow -j | jq -r ".class")"
  xdotool getactivewindow windowunmap
  ;;
  "thunderbird"|"betterbird")
    # If not main window just kill it
    if ! [[ "$(hyprctl activewindow -j | jq --raw-output '.initialTitle')" == "Mozilla Thunderbird" ]]; then
      notify-send "Kill non mail primary window";
      hyprctl dispatch killactive "";
      exit 0
    fi

    # Hide Main Windows via dispatcher ( https://wiki.hyprland.org/Configuring/Dispatchers/ )
    if [[ "$(hyprctl -j monitors | jq --raw-output '.[] | select(.focused==true).activeWorkspace.name')" =~ [M|m]ail ]]; then
      notify-send "Switching Workspace";
      hyprctl dispatch workspace previous;
    else
      notify-send "Move to mail workspace (hide)"
      hyprctl dispatch movetoworkspacesilent name:mail;
    fi
  ;;
  *)
    hyprctl dispatch killactive ""
  ;;
esac

exit 0
