#!/bin/bash

case "$(hyprctl activewindow -j | jq -r ".class")" in
  "steam"|"Microsoft Teams - Preview")
  # Close window to tray
  notify-send "Minimizing App - $(hyprctl activewindow -j | jq -r ".class")"
  xdotool getactivewindow windowunmap
  ;;
  "Mozilla Thunderbird"|"thunderbird"|"betterbird"|"org.mozilla.Thunderbird")
    # If not main window just kill it
    if ! [[ "$(hyprctl activewindow -j | jq --raw-output '.initialTitle')" == "Mozilla Thunderbird" ]]; then
      hyprctl dispatch killactive "";
      exit 0
    fi

    # Hide Main Windows via dispatcher ( https://wiki.hyprland.org/Configuring/Dispatchers/ )
    if [[ "$(hyprctl -j monitors | jq --raw-output '.[] | select(.focused==true).activeWorkspace.name')" =~ [M|m]ail ]]; then
      notify-send "Switched to main workspace";
      old_ws="$(hyprctl activeworkspace | head -n 1 | sed -E 's/^workspace ID ([-]?[0-9]+).*/\1/g')"
      hyprctl dispatch workspace previous;
      if [ "$(old_ws)" == "$(hyprctl activeworkspace | head -n 1 | sed -E 's/^workspace ID ([-]?[0-9]+).*/\1/g')" ]; then
        hyprctl dispatch workspace 1
      fi
    else
      notify-send "Moved thunderbird to mail workspace"
      hyprctl dispatch movetoworkspacesilent name:mail;
    fi
  ;;
  *)
    hyprctl dispatch killactive ""
  ;;
esac

exit 0
