#!/bin/bash

# Note: xdg-desktop-portal: https://wiki.archlinux.org/title/XDG_Desktop_Portal
#       Framework used primarly by Flatpack apps for data access

sleep 4
 killall xdg-desktop-portal-hyprland;
 killall xdg-desktop-portal;
#killall /usr/lib/xdg-desktop-portal.gtk;
 systemctl start --user xdg-desktop-portal-hyprland &
sleep 4
 systemctl start --user xdg-desktop-portal &
#systemctl start --user xdg-desktop-portal-gtk &
