#!/bin/bash

## Files
CONFIG="$HOME/.config/hypr/wofi/config"
STYLE="$HOME/.config/hypr/wofi/style.css"
COLORS="$HOME/.config/hypr/wofi/colors"

## Wofi Command
wofi_command="wofi --show dmenu \
      --conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
      --width=350 --height=380 \
      --cache-file=/dev/null \
      --hide-scroll --no-actions \
      --define=matching=fuzzy"


notification(){
  notify-send "Now Playing: Lofi Radio"
}

menu(){
  printf "00. Gute Musik\n"
  printf "01. 1Live\n"
  printf "02. Lo-Fi Loft\n"
  printf "11. Study\n"
  printf "12. Vibe\n"
  printf "13. Relax\n"
  printf "14. Rebel\n"
  printf "21. Bar\n"
  printf "22. Fantasy\n"
  printf "23. Ship\n"
  printf "24. Space\n"
  printf "31. Stream\n"
  printf "32. Workout\n"
  printf "33. Old\n"
}

main() {
  choice=$(menu | ${wofi_command} | cut -d. -f1)

  case $choice in
    00)
      # Gute Musik
      notification
      mpv --vid=no "https://music.youtube.com/playlist?list=PLhb3OfKIelBAQpoEWqvVaS5ux9r5K29x2"
      return
      ;;
    01)
      # Internet Radio "1Live"
      notification ;
      mpv --vid=no "https://www1.wdr.de/radio/player/einslive-radioplayer-100~_layout-popupVersion.html"
      return
      ;;
    02)
      # Lofi Loft
      notification ;
      mpv --vid=no "https://music.youtube.com/playlist?list=RDCLAK5uy_kb7EBi6y3GrtJri4_ZH56Ms786DFEimbM&playnext=1&si=slttHtVgY0CgVTsR"
      return
      ;;
    11)
      # Study
      notification
      mpv --vid=no "https://www.youtube.com/playlist?list=PLhb3OfKIelBClj5mlYbCaJv-e0iQtfU-s"
      return
      ;;
    12)
      # Vibe
      notification
      mpv --vid=no "https://music.youtube.com/playlist?list=PLhb3OfKIelBD16ngVY4A7Lk8N6gcsmRLD&si=atefCVnCPzWCJEGO"
      return
      ;;
    13)
      # Relax
      notification
      mpv --vid=no "https://music.youtube.com/playlist?list=PLhb3OfKIelBAeH90uhlkRqZCTokSE7MPa&si=YOlulMVX-tfFm0Ax"
      return
      ;;
    14)
      # Rebel
      notification
      mpv --vid=no "https://music.youtube.com/playlist?list=PLhb3OfKIelBBuf6SgusY_Pm1ROC6H38-r&si=18doYBZUcfAM4v-9"
      return
      ;;
    21)
      # Bar
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBA1QX1RDSMe9tUtKrZF7Nb1&si=9PU2s9JW1NBWgNYp"
      return
      ;;
    22)
      # Fantasy
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBB52aSKc1fdtmNKHML335wX&si=t78yCGGK-N2M5zww"
      return
      ;;
    23)
      # Ship
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBBqZPAz49RZvLJ_9iWRRHiW&si=NwvxndGTfg7pJT3L"
      return
      ;;
    24)
      # Space
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBCh-2IANQJWy9AUzn3CXFpb&si=ElD7SCkhA2X-kK5c"
      return
      ;;
    31)
      # Stream
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBDZvBW8L7LsCAHUXBh_3b0p&si=VmmMc5mU2ncLyNIt"
      return
      ;;
    32)
      # Workout
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBDNf_GPn_tzLPCTEaXo3mEG&si=kFMQvrP0A83OQI9F"
      return
      ;;
    33)
      # Old
      notification ;
      mpv --vid=no --shuffle "https://music.youtube.com/playlist?list=PLhb3OfKIelBALv2NWtOR0dELUvnZ-krXR&si=G1jdtEf5FbtCeZLJ"
      return
      ;;
  esac

}

pkill -f http && notify-send "Lofi Radio stopped" || main
