#!/bin/bash
KEYBINDS="/home/$USER/.config/hypr/hyprland-input.conf"

# COLORS
NCL='\033[0m'       # Text Reset
RED='\033[0;31m'    # Red
GRE='\033[0;32m'    # Green
BLU='\033[0;34m'    # Blue

if [ ! -f "$(which glow)" ]; then
  echo "Installing glow"
  yay -S glow
fi
# Output (markdown compatible)
{
 echo "> To exit   press [STRG]+[C] -> [Q]"
 echo "> To search press [/]"
 echo ""
 echo -e "> ${RED}[SUPER]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind[e ]= \$mainMod  "             | sed 's/^.bind[e ]=//g'   | sort ;
  echo ""
  echo -e "> ${RED}[SUPER] + [CTRL]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind[e ]= \$mainMod CTRL  "        | sed 's/^.bind[e ]=//g'   | sort ;
  echo ""
  echo -e "> ${RED}[SUPER] + [SHIFT]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind[e ]= \$mainMod SHIFT  "       | sed 's/^.bind[e ]=//g'   | sort ;
  echo ""
  echo -e "> ${RED}[SUPER] + [ALT]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind[e ]= \$mainMod ALT  "         | sed 's/^.bind[e ]=//g'   | sort ;
  echo ""
  echo -e "> ${RED}[CTRL] + [ALT]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind[e ]= CTRL ALT  "              | sed 's/^.bind[e ]=//g'   | sort ;
  echo ""
  echo -e "> ${RED}[WIN] + [CTRL] + [ALT]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind[e ]= \$mainMod CTRL ALT  " | sed 's/^.bind[e ]=//g'   | sort ;
} | sed 's/|/\\|/g ;
         s/^ /| /g ;
          /[^|]$/s/$/ |/ ;
         s/][^|] |$//g ;
         s/] |/]/g ;
         s/\o33\[0m |/\n| Modifier | Key | Action |\n|:---|:---|:---|/g;
         s/$mainMod[ ]*/WIN /g ;
         s/exec,/EXEC: /g;
         s/ , / | /g ;' \
  | glow | less -R --chop-long-lines

exit 0
