#!/bin/bash
KEYBINDS="/home/$USER/.config/hypr/hyprland-keybinds.conf"

# COLORS
NCL='\033[0m'       # Text Reset
RED='\033[0;31m'    # Red
GRE='\033[0;32m'    # Green
BLU='\033[0;34m'    # Blue

# Output
{\
  echo -e "${RED}[Win]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind = \$mainMod  "       | sed 's/^.bind =//g'   | sort ;\
  echo -e "${RED}[Win] + [CTRL]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind = \$mainMod CTRL  "  | sed 's/^.bind =//g'   | sort ;\
  echo -e "${RED}[Win] + [SHIFT]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind = \$mainMod SHIFT  " | sed 's/^.bind =//g'   | sort ;\
  echo -e "${RED}[Win] + [ALT]${NCL}" &&\
    cat $KEYBINDS | grep "^[^#]bind = \$mainMod ALT  "   | sed 's/^.bind =//g'   | sort ;\
} | sed 's/$mainMod[ ]*/WIN /g;s/ , / | /g' | less -R --chop-long-lines

exit 0
