#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config"
STYLE="$HOME/.config/hypr/waybar/style.css"

toggle_waybar(){
  if [[ ! $(pidof waybar) ]]; then
    echo "Starting waybar"
    nohup waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE} >/dev/null 2>&1&
  else
    echo "Killing waybar"
    pkill waybar
  fi
}

arg=$1
shift 1;
case "$arg" in
 "--help"|"-h")
  echo "this is a help message"
  echo "-w <command> | --wait      ~ run <command> after waybar is detected"
  echo "-h           | --help      ~ show this help message"
  echo "-s           | --status    ~ return 0 if waybar is running, 1 if waybar is not detected"
  echo "                           ~ toggle waybar on/off"
 ;;
 "--wait"|"-w")
  echo "'$@' waiting for waybar"
  while [[ "$(top -bn1 | grep -m 1 -o waybar)" = "" ]];do sleep 1s; done; sleep 1s;
  sleep 1s; nohup $@ >/dev/null 2>/dev/null
;;
 "--status"|"-s")
  return $( [[ "$(top -bn1 | grep -m 1 -o waybar)" == "" ]] && return "0" || return "1" )
 ;;
 "-t"|*)
  toggle_waybar;
 ;;
esac
