#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config"
STYLE="$HOME/.config/hypr/waybar/style.css"

toggle_waybar(){
  if [[ ! $(pidof waybar) ]]; then
    echo "Starting waybar"
    nohup waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE} >/dev/null 2>&1&
  else
    echo "Killing waybar"
    pkill waybar
  fi
}

arg=$1
shift 1;
case "$arg" in
 "--help"|"-h")
  echo "this is a help message"
  echo "-w <command> | --wait      ~ run <command> after waybar is detected"
  echo "-h           | --help      ~ show this help message"
  echo "-s           | --status    ~ return 0 if waybar is running, 1 if waybar is not detected"
  echo "-t           | (default)   ~ toggle waybar on/off"
 ;;
 "--wait"|"-w")
  echo "'$@' waiting for waybar"
  timeout 60 sh -c 'while [[ "$(top -bn1 | grep -m 1 -o waybar)" = "" ]];do sleep 1s; done;' || echo "Reached Timeout, executing program"
  sleep 1s;
  nohup $@ >/dev/null 2>/dev/null &
  disown $(jobs | awk '/nohup/{print $1}' | head -n 1)
;;
 "--status"|"-s")
  return $( [[ "$(top -bn1 | grep -m 1 -o waybar)" == "" ]] && return "0" || return "1" )
 ;;
 "-t"|*)
   if [[ -f "$(which caelestia)" ]]; then
     # Note: This only works when launching via 'qs -c' command
     # Install "caelestia-shell"/"quickshell" for it to work
     pgrep -U "$USER" "qs" >/dev/null && killall -u "$USER" "qs" || qs -c caelestia;
   else
    toggle_waybar;
   fi
 ;;
esac
