#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config"
STYLE="$HOME/.config/hypr/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	echo "Starting waybar"
	nohup waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE} >/dev/null 2>&1&
else
	echo "Killing waybar"
    pkill waybar
fi
