#!/bin/bash

which git && echo "git dependency satisfied" || yay -S git;
which gsettings && echo "gsettings dependency satisfied" || yay -S gnome-control-cente;

## Set GTK Themes, Icons, Cursor and Fonts
catppuccin_theme() {
  #TODO: Install theme if not already installed
  THEME='Catppuccin-Mocha-Standard-Lavender-Dark'
  ICONS='a-candy-beauty-icon-them'
  FONT='SauceCodeProNerdFont'
  CURSOR='Bibata-Modern-Ice'
  SCHEMA='gsettings set org.gnome.desktop.interface'

  ### Custom app theming ###

}

rose-pine_teme() {
  which wget && echo "wget dependency satisfied" || yay -S wget
  [[ -d "~/.config/gtk3/theme/rose-pine-gtk" ]] && echo "rose-pine-gtk dependency satisfied" || yay -S rose-pine-gtk-theme-full;
  THEME='rose-pine-gtk'
  ICONS='rose-pine-icons'
  [[ -z "$(fc-list | grep nerd-fonts-source-space-mono)" ]] && echo "Sauche Code Pro NF Mono dependency satisfied" || yay -S nerd-fonts-source-space-mono; #  (mkdir -p "~/.local/share/fonts/NerdFonts"; cd "~/.local/share/fonts/NerdFonts/"; wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/SpaceMono.zip" && unzip "SpaceMono.zip" );
  FONT="SpaceMonoNerdFont"
  [[ -z "$(find /usr/share/icons ~/.local/share/icons ~/.icons -type d -name 'cursors' | grep rose-pine)" ]] && echo "rose-pine cursor dependency satisfied" || yay -S rose-pine-cursor;
  CURSOR='rose-pine-cursor'

  SCHEMA='gsettings set org.gnome.desktop.interface'

  ### Custom app theming ###
  [[ -f "~/.config/fish/themes/Rosé Pine.theme" ]] || (mkdir -p '~/.config/fish/themes/'; cd '~/.config/fish/themes/'; wget 'https://raw.githubusercontent.com/rose-pine/fish/main/themes/Ros%C3%A9%20Pine.theme'; fish_config theme choose "Rosé Pine");
  # Fish shell theme
}

apply_themes() {
   # Set theme variables
   rose-pine_theme

    #export QT_QPA_PLATFORMTHEME=gtk2
  ${SCHEMA} gtk-theme "$THEME"
  ${SCHEMA} icon-theme "$ICONS"
  ${SCHEMA} cursor-theme "$CURSOR"
  ${SCHEMA} font-name "$FONT"
}

apply_themes
