#!/usr/bin/env bash
# see: https://www.reddit.com/r/hyprland/comments/1bqohmd/dynamically_enabledisable_device/

export TOUCH_DEVICE="wacom-pen-and-multitouch-sensor-finger"

enable_touchpad() {
    hyprctl notify 1 5000 "rgb(ff1ea3)" "Touchpad enabled"
    hyprctl keyword input:touchdevice:enabled true
    hyprctl keyword "device[$TOUCH_DEVICE]:enabled" true
}

disable_touchpad() {
    hyprctl notify 1 5000 "rgb(ff1ea3)" "Touchpad disabled"
    hyprctl keyword input:touchdevice:enabled false
    hyprctl keyword "device[$TOUCH_DEVICE]:enabled" false
}

if [ "$(hyprctl getoption input:touchdevice:enabled | grep int | awk '{print $2}')" == "1" ]; then
  disable_touchpad
else
  enable_touchpad
fi

unset TOUCH_DEVICE
