#!/bin/bash -l

# Restore state of  system before the script was executed
function cleanup() {
  # Note: hyprctl does remove the output but does not lift the output's desktop bind
  hyprctl output remove $(hyprctl monitors | grep -E -o 'HEADLESS-[0-9]+');
  #adb shell dumpsys battery set ac 1; adb shell dumpsys battery set usb 1;
  echo "Cleanup complete"
}

# Enable vnc via usb cable (adb) on android (address: localhost:5900)
# Note: Default VNC port is 5900
function android_usb(){
  if [[ "$(adb devices | grep -v 'List of devices')" != "" ]]; then
    # Forward port to android device
    adb reverse 5900 5900;
  fi
  #adb shell dumpsys battery set ac 0; adb shell dumpsys battery set usb 0;
}

  notify-send "Connect to vnc via $(ip -c -4 addr | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | grep -v "127.0.0.1")";
  echo "Connect to vnc via $(ip -c -4 addr | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | grep -v "127.0.0.1")" &&\
  hyprctl output add headless &&\
    android_usb &&\
    nohup wayvnc --gpu --performance $1 &>/dev/null &&\
      cleanup

# trap cleanup EXIT #force run cleanup on exit (even strg + c)
