-- This is a modified configuration of Arcolinux
-- Modified by 4ctiv
--
-- Please note not all available settings / options are not set here.
-- For more managable files this configuration is split into:
-- - hyprland.conf: This file, holds the main configuration
-- - hyprland-var.conf: Hyprland settings variables (for use in configs)
-- - hyprland-theme.conf: This file holds theme related configurations
-- - hyprland-keybinds.conf: This file holds all keybindings
-- - hyprland-autostart.conf: This file holds startup rules and autostart apps
-- Info @ https://wiki.hyprland.org/

--   ##########################################################################
--  ###    Variables, Definitions, etc.                                    ###
-- ##########################################################################
-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland-var.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-var")

--   ##########################################################################
--  ###    Theming, etc.                                                   ###
-- ##########################################################################
-- See https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#themes
-- Source: ~/.config/hypr/hyprland-theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-theme")

--   ###################
--  ### Environment ###
-- ###################
-- See: https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables

-- Hyprland
hl.env("HYPRCURSOR_SIZE", "24")
  --hl.env("HYPRLAND_NO_RT", "1"
  --hl.env("HYPRLAND_TRACE", "1")
  --hl.env("HYPRLAND_NO_SD_NOTIFY", "1")
  --hl.env("HYPRLAND_NO_SD_VARS", "1")
  --hl.env("HYPRLAND_CONFIG", "~/.config/hypr/hyprland.lua")
-- XDG (if not uwsm session)
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CONFIG_HOME", "$HOME/.config")
-- XWayland
hl.env("XCURSOR_SIZE", "24")

-- GTK/GDK
hl.env("GDK_SCALE", "1")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("GTK_THEME", "gtk_catppuccin-mocha-maroon")
-- QT
hl.env("QT_CURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct") -- qt5ct if using quantum
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
-- Electron
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- Clutter
hl.env("CLUTTER_BACKEND", "wayland")

-- SSH-Agent
  --hl.env("SSH_AUTH_SOCK", os.getenv("XDG_RUNTIME_DIR").."/ssh-agent.socket")

-----------
--- GPU ---
-----------
-- lspci -k | grep VGA # Show avalable GPUs & IDs

-- SDL2 acceleration
hl.env("SDL_VIDEODRIVER", "wayland")

-- Select GPU
-- env = WLR_DRM_DEVICES,"/dev/dri/card1:/dev/dri/card0"

-- GPU: Intel (Arc) Settings
hl.env("VKD3D_CONFIG", "dxr11,dxr")

-- GPU: NVIDIA Settings
-- hl.env("GBM_BACKEND", "nvidia-drm")
-- hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
-- hl.env("LIBVA_DRIVER_NAME","nvidia")

--hl.env("__GL_GSYNC_ALLOWED",1)
--hl.env("__GL_VRR_ALLOWED"  ,0)
--hl.env("WLR_DRM_NO_ATOMIC" ,1)

--   ##########################################################################
--  ###    Monitors, Displays, etc.                                        ###
-- ##########################################################################
-- See https://wiki.hyprland.org/Configuring/Monitors/
require("hyprland-displays")

-------------------------
--- Special Workspace ---
-------------------------

-- Scratchpad
hl.workspace_rule({
    workspace = "special:special",
    on_created_empty = "[workspace special:special; float; size 1900 324; move 10 40; silent; opacity 0.7;] " .. term,
})

hl.curve("overshoot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 10,
    bezier = "overshoot",
    style = "slidefadevert -20%",
})

-- Drawing
hl.workspace_rule({
    workspace = "special:draw",
    gaps_in = 0,
    gaps_out = 0,
    on_created_empty = "[workspace special:draw] which gromit-mpx || " .. term .. " bash -c \"paru -S gromit-mpx\" ; gromit-mpx --active",
  })

-- Screenshot
hl.workspace_rule({
    workspace = "special:screenshot",
    gaps_in = 0,
    gaps_out = 0,
    on_created_empty = screenshot,
})

-- Mail
hl.workspace_rule({
    workspace = "name:mail",
    gaps_in = 0,
    gaps_out = 0,
    on_created_empty = "thunderbird",
})

--------------------------------------------------------------------------------
---                       Hyprland basic configuration                       ---
--------------------------------------------------------------------------------

hl.window_rule({
    match = {
        class = "^(Emulator)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(squeekboard)$",
        title = "^(Squeekboard)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Minecraft Launcher)$",
        title = "^(Minecraft Launcher)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^.*(polkit).*$              title:^(Auth).*$",
    },
    pin = true,
})

hl.window_rule({
    match = {
        title = "^([Pp]icture-in-[Pp]icture)$",
    },
    float = true,
    pin = true,
    no_blur = true,
    no_initial_focus = true,
    size = "(monitor_w*0.25) (monitor_h*0.25)",
    move = "10 (monitor_h*0.75 - 10)",
    opacity = 0.8,
})

hl.window_rule({
    match = {
        class = "^(quickgui)$",
        title = "^(quickgui)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = "^(.*showmethekey(-gtk)?)$",
        title = "^([Ff]loating [Ww]indow -.*)$",
    },
    float = true,
    pin = true,
    size = "(monitor_w*0.6) (monitor_h*0.05)",
    move = "(monitor_w*0.2) (monitor_h*0.92)",
    rounding = 15,
    no_shadow = true,
    border_size = 0,
    no_focus = true,
    no_blur = true,
})

hl.window_rule({
    match = {
        class = "^(net.sapples.LiveCaptions)$",
    },
    float = true,
    pin = true,
    size = "(monitor_w*0.6) (monitor_h*0.05)",
    move = "(monitor_w*0.2) (monitor_h*0.92)",
    opacity = 0.7,
    rounding = 15,
    no_shadow = true,
    border_size = 0,
    no_initial_focus = true,
    no_blur = true,
})

hl.window_rule({
    match = {
        float = 1,
    },
    border_size = 3,
})

hl.window_rule({
    match = {
        class = "(blueberry)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(wofi)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(lutris)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(rnote)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(xournalpp)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(pamac)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(wine)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(update)$",
        title = "^(update)$",
    },
    float = true,
    animation = "popin",
    size = "(monitor_w*0.6) (monitor_h*0.5)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(.*[Ww]aydroid.*)$",
    },
    float = true,
    size = "((monitor_h%1000)*(9/16)) (monitor_h%1000)",
})

hl.window_rule({
    match = {
        class = "^(clock)$",
        title = "^(clock)$",
    },
    float = true,
    size = "(monitor_w*0.33) (monitor_h*0.27)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(galculator)$",
        title = "^(galculator)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*(Calculator).*",
        title = "^(Calculator)$",
    },
    float = true,
    size = "360 620",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal[^ ]*)$",
        title = "^.*([Oo]pen).*$",
    },
    float = true,
    size = "(monitor_w*0.6) (monitor_h*0.5)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^([Gg]romit-mpx)$",
    },
    workspace = "special:draw",
    suppress_event = "fullscreen",
    no_shadow = true,
    border_size = 0,
    no_anim = true,
    no_blur = true,
    no_dim = true,
    float = true,
})

hl.window_rule({
    match = {
        class = "^(flameshot)$",
    },
    workspace = "special:screenshot",
    suppress_event = "fullscreen",
    stay_focused = true,
    no_shadow = true,
    border_size = 0,
    no_anim = true,
    no_blur = true,
    no_dim = true,
    float = true,
    move = "(0) (0)",
    pin = true,
})

hl.window_rule({
    match = {
        class = "^(.*[Pp]apers)$",
    },
    suppress_event = "fullscreen",
})

hl.window_rule({
    match = {
        class = "^(Godot)$",
    },
    float = false,
})


---------------------------------------
---       Input Configuration       ---
---------------------------------------
require("hyprland-input")

---------------------------------------
---      Startup Configuration      ---
---------------------------------------
require("hyprland-autostart")

---------------------------------------
---      General configuration      ---
---------------------------------------
hl.config({
    general = {
        layout = "dwindle", -- dwindle/master/scrolling/monocle
        no_focus_fallback = true,
    },
    -- Per Layout Configuration
    -- See https://wiki.hyprland.org/Configuring/LAYOUT-Layout
    dwindle = {
        preserve_split = true,
    },
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout
        new_on_top = true,
        mfact = 0.5,
    },
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

---------------------------------------
---        MISC Configuration       ---
---------------------------------------
hl.config({
    misc = {
        -- Battery optimisation: enable vfr (variable refresh rate)
        vrr = 3,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        on_focus_under_fullscreen = 2,
        enable_anr_dialog = false, -- Disabe "App not responding" prompts
    },
})


