--   ##########################################################################
--  ###    Monitors, Displays, etc.                                        ###
-- ##########################################################################
-- Configure your Display resolution, offset, scale and Monitors here
--  - Use `hyprctl monitors` to get the info.

--   ####################################
--  ### Variables, Definitions, etc. ###
-- ####################################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
require("hyprland-var")

--   #################
--  ### Rendering ###
-- #################
-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprlock"), { locked = true })

local lMon = "DP-3" -- $(hyprctl monitors -j | jq -r 'min_by(.x).name')
local mMon = "DP-2"
local rMon = "DP-4" -- $(hyprctl monitors -j | jq -r 'max_by(.x).name')
local vMon = "VNC"

----------------
--- Monitors ---
----------------
-- NOTE: ```bitdepth , 10``` may break obs screen-capture
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto-left",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})
hl.monitor({
    output = mMon,
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})
hl.exec_cmd("xrandr --output " .. mMon .. " --primary")
hl.monitor({
    output = vMon,
    mode = "1280x720@30",
    position = "auto-up",
    scale = "1",
    transform = 0,
    vrr = 1,
})
hl.monitor({
    output = lMon,
    mode = "1920x1080@60",
    position = "auto-left",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})
hl.monitor({
    output = rMon,
    mode = "1920x1080@60",
    position = "auto-right",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

------------------
--- Workspaces ---
------------------
hl.workspace_rule({
    workspace = "2",
    monitor = mMon,
    default = true,
})

-------------------------------
--- Portable Device Configs ---
-------------------------------
-- On lid close
--bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
-- On lid open
--bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 1"

-- Enable auto-rotation (requires iio-hyprland)
-- NOTE: Use custom fork that supports lua config
hl.dsp.exec_cmd("iio-hyprland") -- laptop: monitor auto-rotation

------------
--- MISC ---
------------

-- Focus Primary monitor (startup)
hl.dsp.exec_cmd("hyprctl dispatch focusmonitor " .. mMon)

-- Screen sharing
-- See https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland
-- -> ~/.config/hypr/xdph.conf

hl.config({
    xwayland = {
        force_zero_scaling = true,
        create_abstract_socket = true,
    },
    render = {
        direct_scanout = 2,
        cm_auto_hdr = 1,
        new_render_scheduling = true,
    },
})

