--   ##########################################################################
--  ###    Startup rules, etc.                                             ###
-- ##########################################################################
-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

--   ####################################
--  ### Variables, Definitions, etc. ###
-- ####################################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland-var.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-var")

--exec-once = $scriptsDir/gamemode    &  # Also saves battery power

--   ########################
--  ### Systemd services ###
-- ########################
--exec-once = systemctl start --user {docker,podman}.service &     # container manager (rootless)

--   ###################
--  ### Dirty Fixes ###
-- ###################

-- Setup xauthority user conf if needed (xwayland)

-- Connect polkit (PolicyKit)

-- Setup virtual audio cables
--exec-once = $scriptsDir/audio_setup &

-- Mute audio on login

-- Disable Bluetooth on login

-- Allow root apps GUI access

-- Fix Slow app launch

-- Fix 802.11ac (Driver DVD mode)
--exec-once = sleep 5s && $scriptsDir/Fix_rtl_CD_modeswitch.sh

-- Start ~/.config/autostart/*.desktop files (desktop startup apps)

-- Start auto upgrade

--   #################
--  ### Clipboard ###
-- #################
-- NOTE: When xwayland apps have issues with clipboard try reinstalling `xorg-xwayland`

-- Sync xwayland & wayland clipboard (since Hyprland 0.40.2)

--   ######################
--  ### Autostart Apps ###
-- ######################
-- source = ~/.config/hypr/hyprland-autostart.conf
--
-- Note: To exec after waybar is ready:
--   exec-once = nohup $scriptsDir/statusbar -w COMMAND COMMAND_ARGS >/dev/null 2>&1

-- System Tray Apps
--exec-once = blueman-applet           &
--exec-once = flameshot                &
--exec-once = kdeconnect-applet        &

-- File management
--exec-once = nextcloud --backround                     &
--exec-once = nextcloud --background                    &
--exec-once = seafile-applet                            &
--exec-once = /usr/bin/cells-sync-bin-ui-launcher.sh -q &

-- Games
--exec-once = lutris &
--exec-once = steam  -silent &
--exec-once = heroic -silent -nopipewire &

-- Communication
--exec-once = noisetorch  -i                           & # Microphone noise reduction
--exec-once = discord --start-minimized                & # Voice chat
--exec-once = ferdium                                  & # AiO Socials
--exec-once = signal-desktop      --start-in-tray      & # Secure chat
--exec-once = telegram-desktop     -startintray        & # group chat
--exec-once = whatsapp-nativefier                      & # insecure chat
           -- Whatsapp startup tray: ```sed -i 's/"tray": "true"/"tray": "start-in-tray"/g' /opt/whatsapp-nativefier/resources/app/nativefier.json```

hl.on("hyprland.start", function()
    hl.exec_cmd("$scriptsDir/core-software-setup")
    hl.exec_cmd("systemctl start --user xdg-desktop-portal-hyprland.service &")
    hl.exec_cmd("systemctl start --user xdg-desktop-portal-gtk.service      &")
    hl.exec_cmd("systemctl start --user xdg-desktop-portal.service          &")
    hl.exec_cmd("systemctl start --user gnome-keyring-daemon.socket &")
    hl.exec_cmd("systemctl start --user hyprsunset.service &")
    hl.exec_cmd("systemctl start --user hyprpaper.service  &")
    hl.exec_cmd("systemctl start --user hypridle.service   &")
    hl.exec_cmd("systemctl start --user ssh-agent.service &")
    hl.exec_cmd("systemctl start --user gpg-agent.service &")
    hl.exec_cmd("systemctl start --user pipewire.service  &")
    hl.exec_cmd("systemctl start --user waybar.service &")
    hl.exec_cmd("systemctl start --user mako.service   &")
    hl.exec_cmd("|| xauth gen $DISPLAY >/dev/null", { ["-f"] = "$(xauth -q info | awk '/Authority file/{print $3}')" })
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")
    hl.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ 1 &")
    hl.exec_cmd("bluetoothctl power off &")
    hl.exec_cmd("xhost si:localuser:root &")
    hl.exec_cmd("systemctl --user import-environment &")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null &")
    hl.exec_cmd("dbus-update-activation-environment --systemd &")
    hl.exec_cmd("$scriptsDir/autostart_desktop.sh")
    hl.exec_cmd("$scriptsDir/auto-upgrade &")
    hl.exec_cmd("wl-paste --type text  --watch cliphist store &")
    hl.exec_cmd("wl-paste --type image --watch cliphist store &")
    hl.exec_cmd("cliphist wipe &")
    hl.exec_cmd("$scriptsDir/fix_clipboard_xwayland.sh &")
    hl.exec_cmd("nm-applet --indicator    &")
    hl.exec_cmd("openrgb --startminimized &")
    hl.exec_cmd("keepassxc --minimized                     &")
    hl.exec_cmd("thunderbird &", { workspace = "name:mail silent" })
    hl.exec_cmd("cinny       &", { workspace = "name:chat silent" })
end)

