-- ##########################################################################
--  ##########################################################################
--   ###    Hotkeys, Keybindings, etc. for hyprland                         ###
--  ##########################################################################
-- ##########################################################################

-- ########################
-- # Flag # Description   # Syntax: bind[FLAG] = (...,)*
-- ###########################################################################################
-- # l    # locked        # works also when in input inhibitor (e.g. lockscreen) is active   #
-- # r    # release       # will trigger on release of a key.                                #
-- # e    # repeat        # will repeat when held.1                                          #
-- # n    # non-consuming # key/mouse events, passed to active window and triggers dispatcher#
-- # m    # mouse         # see below                                                        #
-- # t    # transparent   # cannot be shadowed by other binds                                #
-- ###########################################################################################
-- # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
-- # NOTE: [ALT]=ALT ; [CTRL]=CTRL ; [ENTER]=RETURN ; [SHIFT]=SHIFT ; [WIN]=SUPER
-- # NOTE: 'exec-once' to launch applications / daemons on boot
-- #       'exec'      to launch applications           on reload
-- #       'bind'      hotkey assignment
-- #       'env'       set environment variable (different syntax than 'env' in UNIX)

-- Note: How to launch programs and install them when they are not installed currently
--  - which PROGRAM && INSTALLED || INSTALL
--  - which PROGRAM || INSTALL ; RUN

-- Note: Launch programs with dispatchers via hyprctl `[displatcher;...] program args`
-- ... , exec, [workspace special; silent; rounding 3;opacity 0.7;float;noanim;pin;move 1% 43px;size 98% 300px;focus 1] $term

--   ####################################
--  ### Variables, Definitions, etc. ###
-- ####################################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland-var.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-var")

--   ########################
--  ### Input & Gestures ###
-- ########################
-- For all categories, see https://wiki.hyprland.org/Configuring/Variables

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
hl.gesture({
    fingers = 3,
    direction = "up",
    action = function() hl.dsp.exec_cmd(fullmenu, { stay_focused = true }) end,
})
hl.gesture({
    fingers = 3,
    direction = "down",
    action = "special",
})

hl.device({
    name = "wacom-pen-and-multitouch-sensor-finger",
    enabled = TOUCH_ENABLED,
})

hl.device({
    name = "elan-trackpoint",
    enabled = KNOB_ENABLED,
})

hl.device({
    name = "elan-touchpad",
    sensitivity = 1.0,
    enabled = PAD_ENABLED or not KNOB_ENABLED,
})

hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("kitty $scriptsDir/show-keybinds"))
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + F4", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd(mail))
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd(messanger))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd(zoom .. " 0.2"))
hl.bind(mainMod .. " + SHIFT + F7", hl.dsp.exec_cmd(zoom .. " -0.2"))
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("gromit-mpx --undo"))
hl.bind(mainMod .. " + SHIFT + F8", hl.dsp.exec_cmd("gromit-mpx --redo"))
hl.bind(mainMod .. " + F9", hl.dsp.exec_cmd(audio))
hl.bind(mainMod .. " + F10", hl.dsp.exec_cmd(photo))
hl.bind(mainMod .. " + F11", hl.dsp.exec_cmd(video))
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd(keyboard))

hl.bind(mainMod .. " + KP_End", hl.dsp.exec_cmd("notify-send \"Starting Windows VM ...\" && cd $qemuDir && ( [[ ! -d \"windows-10\"          ]] && $term quickget windows 10          || notify-send \"Config found\" ) && quickemu --display spice --vm windows-10.conf"))
hl.bind(mainMod .. " + KP_Down", hl.dsp.exec_cmd("notify-send \"Starting Ubuntu  VM ...\" && cd $qemuDir && ( [[ ! -d \"ubuntu-24.04\"        ]] && $term quickget ubuntu 24.04        || notify-send \"Config found\" ) && quickemu --display spice --vm ubuntu-24.04.conf"))
hl.bind(mainMod .. " + KP_Next", hl.dsp.exec_cmd("notify-send \"Starting Macos   VM ...\" && cd $qemuDir && ( [[ ! -d \"macos-sonoma\"        ]] && $term quickget macos sonoma        || notify-send \"Config found\" ) && quickemu --display spice --vm macos-sonoma.conf"))
hl.bind(mainMod .. " + KP_Begin", hl.dsp.exec_cmd("quickgui"))

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(term))
hl.bind(mainMod .. " + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("pavucontrol"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("blueman-manager"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(transcriber))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(scriptsDir .. "/changeLayout" ))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd(notify_hist))
hl.bind(mainMod .. " + S", hl.dsp.group.toggle())
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("notify-send \"Window info\" \"$(echo -e \"$(hyprctl activewindow -j | jq -r '\"\\(.title | .[:20]) [\\(.class)] \\\\n PID: \\(.pid); WS: \\(.workspace.name) [\\(.workspace.id)]\"')\")\""))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(keylogger))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(scriptsDir .. "/ollama"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("notify-send \"Monitor info\" \"$(hyprctl monitors -j | jq -r '.[] | \"Monitor: \\\\(.name)[\\\\(.id)]@\\\\(.activeWorkspace.name)[\\\\(.activeWorkspace.id)]\\\\\\\\nResolution: \\\\(.width)x\\\\(.height)@\\\\(.refreshRate | floor ) (\\\\(.scale))\"' | grep -F \"$(hyprctl activeworkspace -j | jq -r '. | \"Monitor: \\\\(.monitor)\"')\")\""))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian || (kitty sh -c 'yay -S obsidian' && obsidian)"))
hl.bind(mainMod .. " + P", hl.dsp.window.pin())
hl.bind(mainMod .. " + Q", hl.dsp.window.close()) -- hl.dsp.exec_cmd(kill_active))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(wofi_beats))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(scriptsDir.. "/toggle_touch touch"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(clip_hist))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(fullmenu, {stay_focused = true}))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd(fullmenu, {stay_focused = true}))

hl.bind(mainMod .. " + SHIFT + Escape", hl.dsp.exec_cmd(term .. " --class bashtop -T bashtop -e bashtop"))
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("killall easyeffects && easyeffects"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.center())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd(term .. " --class clock -T clock -e tty-clock -c -C 7 -r -s -f \"%A, %B, %d\""))

hl.bind(mainMod .. " + CTRL + Space", hl.dsp.exec_cmd(scriptsDir .. "/changeLayout"))
hl.bind(mainMod .. " + CTRL + A", hl.dsp.exec_cmd(term .. " --class cava -T cava -e cava"))
hl.bind(mainMod .. " + CTRL + B", hl.dsp.exec_cmd(term .. " --class bonsai -T bonsai -e bash -c 'while true; do cbonsai -S -l; sleep 1s; done'"))
hl.bind(mainMod .. " + CTRL + C", hl.dsp.exec_cmd(term .. " --class clock -T clock -e tty-clock -c -C 7 -r -s -f \"%A, %B, %d\""))
hl.bind(mainMod .. " + CTRL + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))
hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd(lock))
hl.bind(mainMod .. " + CTRL + P", hl.dsp.exec_cmd("pin"))
hl.bind(mainMod .. " + CTRL + Q", hl.dsp.exec_cmd("killall wlogout; wlogout -l ~/.config/hypr/wlogout/layout -c ~/.config/hypr/wlogout/style.css"))
hl.bind(mainMod .. " + CTRL + S", hl.dsp.exec_cmd("exec hyprctl dispatch movewindoworgroup r"))
hl.bind(mainMod .. " + CTRL + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + CTRL + T", hl.dsp.exec_cmd(scriptsDir .. "/toggle_touch knob"))

hl.bind(mainMod .. " + ALT + A", hl.dsp.exec_cmd("bash -c 'pidof \"handy\" >/dev/null || (handy&) ; sleep 1s; handy --toggle-transcription'"))
hl.bind(mainMod .. " + ALT + B", hl.dsp.exec_cmd(brightness .. " --filter"))
hl.bind(mainMod .. " + ALT + C", hl.dsp.exec_cmd(colorpicker))
hl.bind(mainMod .. " + ALT + F", hl.dsp.exec_cmd(statusbar))
hl.bind(mainMod .. " + ALT + G", hl.dsp.exec_cmd(gamemode))
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd(lock))
hl.bind(mainMod .. " + ALT + M", hl.dsp.exec_cmd(speak_toggle .. " && notify-send -t 1000 \"Mic $(pactl get-source-mute @DEFAULT_SOURCE@)\""))
hl.bind(mainMod .. " + ALT + N", hl.dsp.exec_cmd(sound_toggle .. " && notify-send -t 1000 \"Aux $(pactl get-sink-mute @DEFAULT_SINK@)\""))
hl.bind(mainMod .. " + ALT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + ALT + T", hl.dsp.exec_cmd(scriptsDir .. "/toggle_touch pad"))

hl.bind(mainMod .. " + CTRL + ALT + Up", hl.dsp.exec_cmd(   brightness .. " --inc"), { repeating = true })
hl.bind(mainMod .. " + CTRL + ALT + Down", hl.dsp.exec_cmd( brightness .. " --dec"), { repeating = true })
hl.bind(mainMod .. " + CTRL + ALT + Right", hl.dsp.exec_cmd(volume .. " +5%"), { repeating = true })
hl.bind(mainMod .. " + CTRL + ALT + Left", hl.dsp.exec_cmd( volume .. " -5%"), { repeating = true })

hl.bind(mainMod .. " + CTRL + SHIFT + Escape", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind("ALT + F4", hl.dsp.exec_cmd("kill -9 $(hyprctl activewindow -j | jq '.pid')"))
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd(term .. " htop"))
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd(term .. " htop"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd(screenshot))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd(screenshot))

hl.bind(mainMod .. " + W", hl.dsp.workspace.toggle_special("special"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.window.float({ action = "set" }))
hl.bind(mainMod .. " + G", hl.dsp.workspace.toggle_special("draw"))
hl.bind("CTRL + SHIFT + Z", hl.dsp.exec_cmd("gromit-mpx --undo"))
hl.bind("CTRL + SHIFT + R", hl.dsp.exec_cmd("gromit-mpx --redo"))
hl.bind(mainMod .. " + tab", hl.dsp.group.next())
hl.bind(mainMod .. " + SHIFT + tab", hl.dsp.group.prev())
hl.bind("ALT + tab", hl.dsp.focus({ workspace = "m+1" }))
hl.bind("ALT + SHIFT + tab", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mainMod .. " + CTRL + Return", hl.dsp.layout("swapwithmaster"))
hl.bind(mainMod .. " + CTRL + M", hl.dsp.layout("addmaster"))
hl.bind(mainMod .. " + CTRL + N", hl.dsp.layout("removemaster"))

hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + ALT + up", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + ALT + down", hl.dsp.focus({ workspace = -1 }))
hl.bind(mainMod .. " + ALT + left", hl.dsp.focus({ workspace = -1 }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 00, y = -50, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 00, y = 50, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -50, y = 00, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 50, y = 00, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ into_or_create_group = "r" }))

hl.bind(mainMod .. " + minus", hl.dsp.focus({ direction = 'l' }))
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + plus", hl.dsp.focus({ direction = 'r' }))
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = -1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + plus", hl.dsp.window.move({ workspace = "+1", follow = false }))
hl.bind(mainMod .. " + CTRL + minus", hl.dsp.window.move({ workspace = -1 }))
hl.bind(mainMod .. " + CTRL + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + CTRL + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + CTRL + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + CTRL + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + CTRL + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + CTRL + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + CTRL + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + CTRL + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + CTRL + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + CTRL + +", hl.dsp.window.move({ workspace = "+1" }))

hl.bind("xf86audiomute", hl.dsp.exec_cmd(sound_toggle))
hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd(volume .. " +5%"))
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd(volume .. " -5%"))
hl.bind("xf86audioplay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("xf86audiostop", hl.dsp.exec_cmd("playerctl stop"))
hl.bind("xf86audionext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("xf86audioprev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd(brightness .. " --inc"))
hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd(brightness .. " --dec"))
hl.bind(mainMod .. " + SHIFT + equal", hl.dsp.submap("backlight"))
hl.define_submap("backlight", function()
    hl.bind("equal", hl.dsp.exec_cmd(backlight .. " --inc"))
    hl.bind("minus", hl.dsp.exec_cmd(backlight .. " --dec"))
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + equal", hl.dsp.submap("volume"))
hl.define_submap("volume", function()
    hl.bind("equal", hl.dsp.exec_cmd(volume .. " +5%"))
    hl.bind("minus", hl.dsp.exec_cmd(volume .. " -5%"))
    hl.bind(0, hl.dsp.exec_cmd(sound_toggle))
    hl.bind(9, hl.dsp.exec_cmd(speak_toggle))
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + period", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + comma", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + comma", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + period", hl.dsp.workspace.toggle_special(""))
hl.bind(mainMod .. " + minus", hl.dsp.focus({ workspace = "e+1" }))

hl.config({
    binds = {
        workspace_back_and_forth = true,
        --workspace_center_on = 1
        disable_keybind_grabbing = true, -- Disable e.g. VM input grabbing
    },
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/#gestures
        -- Universal
        workspace_swipe_use_r = false, -- false -> Skip unused workspaces in betwwen used
        workspace_swipe_forever = false, -- false -> swip until last ws not further
        workspace_swipe_create_new = true, -- true  -> swipe create ws (limit to 1 if swipe_forever is true)
        -- Nothing ?
        workspace_swipe_direction_lock = true,
        workspace_swipe_direction_lock_threshold = 10,
        workspace_swipe_min_speed_to_force = 100,
        -- Touch screen (tablet)
        workspace_swipe_touch = true,
        workspace_swipe_cancel_ratio = 0.5,
        -- Trackpad (laptop)
        workspace_swipe_distance = 100,
        workspace_swipe_invert = true,
        --gesture = fingers, direction , action   [, options]
    },
    input = {
        -- Keyboard settings
        kb_layout = "de,us", -- localectl list-x11-keymap-layouts
        --kb_variant = euro,us # localectl list-x11-keymap-variants
        kb_options = "grp:caps_toggle,fkeys:basic_13-24",
        numlock_by_default = true,
        resolve_binds_by_sym = 1, -- kb_layout -1-> affect keybinds
        -- Mouse setings
        follow_mouse = true,
        sensitivity = -0.7, -- -1.0 - 1.0, 0 means no modification
        force_no_accel = true, -- Disable mouse acceleration
        -- touchpad ~ Laptop mouse area
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            --scroll_factor = 1.0
            middle_button_emulation = true,
            --tab_button_map = l
            --clickfinger_behaviour = false
            tap_to_click = true,
            drag_lock = true,
        },
        -- touchdevice ~ Capacitive touchscreen (touch)
        touchdevice = {
            --transform = 0
            enabled = true,
            output = "eDP-1",
        },
        -- Tablet ~ Active Pen device
        tablet = {
            --transform = 0
            output = "eDP-1",
            --region_position = 0 0
            --region_size = 1920 1080
            --relative_input = false
            --left_handed = false
            --active_area_size = [1920,1080]
            --active_area_position = [0,0]
        },
    },
    --## Devcie specific toggles & settings
    -- https://github.com/hyprwm/Hyprland/discussions/4283?sort=new
    -- Touchscreen
    -- Thinkpad track knob
    -- Thinkpad touchpad
    --   ###########
    --  # Hotkeys #
    -- ###########
    -- Hotkey alias
    -- [WIN] + [Fn]
    -- Stack 1: basic tools
    -- Stack 2: Communication
    -- Stack 3: Micilanious
    -- Launch VM's using quickemu (Arch dep's: quemu, qemu-desktop, quickgui) numpad see: https://www.reddit.com/r/hyprland/comments/11zy9tj/binding_numpad_keys_to_switch_workspaces/
    -- NOTE: VM's have to be installed in the given directory by running 'quickget VM_NAME VM_VESRION' e.g.: 'quickget ubuntu 22.04'
    -- NOTE: KP_... (number-pad *) only active when 'numlock_by_default = true'
    --bind = $mainMod           , KP_Insert   , exec, notify-send "Starting _______ VM ..." && cd $qemuDir && ( [[ ! -f "manjaro-budgie.conf" ]] && $term quickget ___________ _____   || notify-send "Config found" ) && quickemu --display spice --vm ________-____.conf          #NumPad0
    --bind = $mainMod           , KP_Left     , exec, notify-send "Starting Android VM ..." && cd $qemuDir && ( [[ ! -d "android-9.0-x86_64"  ]] && $term quickget android 9.0 x86_64  || notify-send "Config found" ) && quickemu --display spice --vm ubuntu-daily-live.conf      #NumPad4
    --bind = $mainMod           , KP_Right    , exec, notify-send "Starting Arch    VM ..." && cd $qemuDir && ( [[ ! -d "archlinux-latest"    ]] && $term quickget archlinux latest    || notify-send "Config found" ) && quickemu --display spice --vm archlinux-latest.conf       #NumPad6
    --bind = $mainMod           , KP_UP       , exec, notify-send "Starting Parrot  VM ..." && cd $qemuDir && ( [[ ! -d "parrotsec-security"  ]] && $term quickget parrotsec 6.1 security || notify-send "Config found" ) && quickemu --display spice --vm kali-current.conf        #NumPad7
    --bind = $mainMod           , KP_Home     , exec, notify-send "Starting Arch    VM ..." && cd $qemuDir && ( [[ ! -d "archlinux-latest"    ]] && $term quickget archlinux latest    || notify-send "Config found" ) && quickemu --display spice --vm archlinux-latest.conf       #NumPad8
    --bind = $mainMod           , KP_Prior    , exec, notify-send "Starting NixOS   VM ..." && cd $qemuDir && ( [[ ! -d "nixos-23.11-minimal" ]] && $term quickget nixos 23.11 minimal || notify-send "Config found" ) && quickemu --display spice --vm nixos-23.11-minimal.conf    #NumPad9
    -- [WIN]
    -- [Win] + [SHIFT]
    -- [WIN] + [CTRL]
    -- [WIN] + [ALT]
    -- [CTRL] + [ALT] (Core Software)
    -- Backlight control (supported screens only)
    -- [Win] + [CTRL] + [SHIFT] (For things that do not be pressed exedentally)
    -- WINDOWS BINDS
    -- Screenshot keybindings
    --   ##################################
    --  ## Window & Workspace controll ###
    -- ##################################
    -- "Scratchpad" Workspace (Quick window overlay)
    -- "Hide" Workspace (Toggle window hide)
    --bind = $mainMod           , H           , togglespecialworkspace, minimize
    --bind = $mainMod           , H           , movetoworkspace, +0
    --bind = $mainMod           , H           , togglespecialworkspace, minimize
    --bind = $mainMod           , H           , movetoworkspace, special:minimize
    --bind = $mainMod           , H           , togglespecialworkspace, minimize
    -- "Draw" Workspace (Draw on screen)
    -- Workspace cycle
    -- Master Stack
    -- #####################
    -- ## Core navigation ##
    -- #####################
    -- Focus window
    -- Focus workspace
    -- Resize window
    -- Move window
    -- Switch workspaces [WIN] + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Move active window and follow to workspace
    --   #####################
    --  # Special controlls #
    -- #####################
    -- Audio controlls
    -- Display controlls
    -- Volume control
    --   ###################
    --  # Mouse controlls #
    -- ###################
    -- Scroll through existing workspaces
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    --   ###################
    --  # Other controlls #
    -- ###################
    -- Personal vscode like controlls
})

