#   ##########################################################################
#  ###    Monitors, Displays, etc.                                        ###
# ##########################################################################
# Configure your Display resolution, offset, scale and Monitors here
#  - Use `hyprctl monitors` to get the info.

#   ####################################
#  ### Variables, Definitions, etc. ###
# ####################################
source = ~/.config/hypr/hyprland-var.conf

#   #################
#  ### Rendering ###
# #################
# See https://wiki.hyprland.org/Configuring/Monitors/

# Prevent wayland scaling issues
xwayland {
  force_zero_scaling = true
  create_abstract_socket = true
}

render {
  direct_scanout = 2
  cm_auto_hdr = 1
  new_render_scheduling = true
}

# Screen sharing options
# File: ~/.config/hypr/xdph.conf
# See https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland

# Enable auto-rotation (requires iio-hyprland)
 exec-once = iio-hyprland # wlr-autorotate -m -eDP-1

# Laptop lid close trigger
# Disable on close
 bindl = , switch:on:Lid  Switch,exec,hyprctl keyword monitor "eDP-1, disable"
# Enable on open
 bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 1"

#   #######################
#  # Multi-Monitor Setup #
# #######################
# NOTE: Adding ```bitdepth , 10``` to ```monitor = ...``` breaks obs screen-capture
# Multi monitor scaling calculation
 $dp_abs_offset = 420               # 420 ~ ( max_H - min_H )
 $dp_h_scale    = 1.2               # 1.2 ~ $dp_abs_scale * ( $monitor_max_scale / $monitor_min_scale )
 $dp_h_offset   = 275               # 240 ~ ( 1 / $dp_hp_scale) * $dp_abs_offset

 $lMon=DP-2 # $(hyprctl monitors -j | jq -r 'min_by(.x).name')
 $mMon=DP-3
 $rMon=DP-4 # $(hyprctl monitors -j | jq -r 'max_by(.x).name')
 $vMon=VNC
# Primary monitor (xwayland compatability)
 exec-once = xrandr --output $mMon --primary

# Cursor on Main Monitor (session start)
 exec-once = hyprctl dispatch focusmonitor $mMon
# Window on Main Monitor (new)
 exec-once = xrandr --output $mMon --primary # primary monitor (xwayland)

# Default monitor
 monitor     =                     , preferred     , auto-left  , 1 , transform, 0, vrr, 1, cm, auto

# Virtual monitor (VNC)
 monitor     = $vMon               , 1280x720@30   , auto-up    , 1 , transform, 0, vrr, 1

# Main Monitor
 monitor     = $mMon               , 1920x1080@60 ,    0x0         , 1, transform, 0, vrr, 1, cm, auto
   workspace = 1, monitor:$mMon    , default:true

# Left Monitor
#monitor     = $lMon               , 1920x1080@60   , auto-left  , 1 , transform, 0, vrr, 1

# Right Monitor
#monitor     = $rMon               , 1920x1080@60   , auto-right  , 1 , transform, 0, vrr, 1

#### CUSTOM CONFIG (Docks etc.)
