-- This is a modified configuration of Arcolinux
-- Modified by 4ctiv
--
-- Please note not all available settings / options are not set here.
-- For more managable files this configuration is split into:
-- - hyprland.conf: This file, holds the main configuration
-- - hyprland-var.conf: Hyprland settings variables (for use in configs) 
-- - hyprland-theme.conf: This file holds theme related configurations
-- - hyprland-keybinds.conf: This file holds all keybindings
-- - hyprland-autostart.conf: This file holds startup rules and autostart apps
-- Info @ https://wiki.hyprland.org/

--   ##########################################################################
--  ###    Variables, Definitions, etc.                                    ###
-- ##########################################################################
-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland-var.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-var")

--   ##########################################################################
--  ###    Theming, etc.                                                   ###
-- ##########################################################################
-- See https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#themes
-- Source: ~/.config/hypr/hyprland-theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-theme")

--   #############################
--  ### Environment variables ###
-- #############################
-- See: https://wiki.hyprland.org/Configuring/Environment-variables/
--debug{
--  disable_logs = false
--  disable_time = false
--  enable_stdout_logs = true
--  colored_stdout_logs = true
--}

-- Hyprland settings
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRLAND_TRACE", "1")
hl.env("HYPRLAND_LOG_WLR", "1")
-- XDG settings
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CONFIG_HOME", "$HOME/.config")
-- GTK settings
hl.env("GTK_THEME", "gtk_catppuccin-mocha-maroon")
hl.env("GDK_BACKEND", "wayland,x11")
-- QT settings
hl.env("QT_CURSOR_SIZE", "24")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
-- Clutter settings
hl.env("CLUTTER_BACKEND", "wayland")
-- Electron settings
-- (> Electron 28) "--enable-features=UseOzonePlatform --ozone-platform=wayland"
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- XWayland setting
hl.env("XCURSOR_SIZE", "24")

--   ###################
--  # Default software #
-- ####################
--            xdg-mime default PROGRAM.desktop          mime/type
--exec-once = xdg-mime default nemo.desktop             inode/directory
--exec-once = xdg-mime default inkscape.desktop         image/svg+xml
--exec-once = xdg-mime default gimp.desktop             image/png
--exec-once = xdg-mime default org.gnome.Papers.desktop application/pdf
--                            #com.github.xournalpp.xournalpp.desktop application/pdf
--exec-once = xdg-mime default google-chrome.desktop    x-scheme-handler/zoommtg

--   ################
--  # Hyprland GPU #
-- ################
-- lspci -k | grep VGA && wlr-randr --dryrun # Show avalable GPU's ID

-- Select GPU
-- env = WLR_DRM_DEVICES,"/dev/dri/card1:/dev/dri/card0" # gpu usage policy: gpu0 > gpu1

-- GPU: Intel Arc hw-raytracing support
hl.env("VKD3D_CONFIG", "dxr11,dxr")

-- GPU: SDL2 applications on Wayland
hl.env("SDL_VIDEODRIVER", "wayland")

-- GPU: NVIDIA Settings
--env = GBM_BACKEND,nvidia-drm
--env = __GLX_VENDOR_LIBRARY_NAME,nvidia
--env = LIBVA_DRIVER_NAME,nvidia
--env = __GL_GSYNC_ALLOWED,1
--env = __GL_VRR_ALLOWED,0
--env = WLR_DRM_NO_ATOMIC,1

--   ################
--  #  Text Input  #
-- ################
-- IME Support: fcitx (need to be installed)
--env = GTK_IM_MODULE=fcitx
--env = QT_IM_MODULE=fcitx
--env = XMODIFIERS=@im=fcitx
--env = SDL_IM_MODULE=fcitx
--env = GLFW_IM_MODULE=ibus

--   ##########################################################################
--  ###    Monitors, Displays, etc.                                        ###
-- ##########################################################################
-- Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.
-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Source: ~/.config/hypr/hyprland-displays.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-displays")

--   #####################
--  # Special Workspace #
-- #####################

-- special workspace (Scratchpad)
hl.workspace_rule({
    workspace = "special:special",
    on_created_empty = "[workspace special:special; float; size 1900 324; move 10 40; silent; opacity 0.7;] " .. term,
})

hl.curve("overshoot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 10,
    bezier = "overshoot",
    style = "slidefadevert -20%",
})
-- overlay  workspace
hl.workspace_rule({
    workspace = "special:draw",
    gaps_in = 0,
    gaps_out = 0,
    on_created_empty = "[workspace special:draw] which gromit-mpx || " .. term .. " bash -c \"paru -S gromit-mpx\" ; gromit-mpx --active",
  })

hl.workspace_rule({
    workspace = "special:screenshot",
    gaps_in = 0,
    gaps_out = 0,
    on_created_empty = screenshot,
})

-- mail workspace
hl.workspace_rule({
    workspace = "name:mail",
    gaps_in = 0,
    gaps_out = 0,
    on_created_empty = "thunderbird",
})

--   ##########################################################################
--  ###    Hyprland basic configurations                                   ###
-- ##########################################################################

hl.window_rule({
    match = {
        class = "^(Emulator)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(squeekboard)$",
        title = "^(Squeekboard)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Minecraft Launcher)$",
        title = "^(Minecraft Launcher)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^.*(polkit).*$              title:^(Auth).*$",
    },
    pin = true,
})

hl.window_rule({
    match = {
        title = "^([Pp]icture-in-[Pp]icture)$",
    },
    float = true,
    pin = true,
    no_blur = true,
    no_initial_focus = true,
    size = "(monitor_w*0.25) (monitor_h*0.25)",
    move = "10 (monitor_h*0.75 - 10)",
    opacity = 0.8,
})

hl.window_rule({
    match = {
        class = "^(quickgui)$",
        title = "^(quickgui)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = "^(.*showmethekey(-gtk)?)$",
        title = "^([Ff]loating [Ww]indow -.*)$",
    },
    float = true,
    pin = true,
    size = "(monitor_w*0.6) (monitor_h*0.05)",
    move = "(monitor_w*0.2) (monitor_h*0.92)",
    rounding = 15,
    no_shadow = true,
    border_size = 0,
    no_focus = true,
    no_blur = true,
})

hl.window_rule({
    match = {
        class = "^(net.sapples.LiveCaptions)$",
    },
    float = true,
    pin = true,
    size = "(monitor_w*0.6) (monitor_h*0.05)",
    move = "(monitor_w*0.2) (monitor_h*0.92)",
    opacity = 0.7,
    rounding = 15,
    no_shadow = true,
    border_size = 0,
    no_initial_focus = true,
    no_blur = true,
})

hl.window_rule({
    match = {
        float = 1,
    },
    border_size = 3,
})

hl.window_rule({
    match = {
        class = "(blueberry)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(wofi)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(lutris)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(rnote)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "(xournalpp)",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(pamac)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(wine)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(update)$",
        title = "^(update)$",
    },
    float = true,
    animation = "popin",
    size = "(monitor_w*0.6) (monitor_h*0.5)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(.*[Ww]aydroid.*)$",
    },
    float = true,
    size = "((monitor_h%1000)*(9/16)) (monitor_h%1000)",
})

hl.window_rule({
    match = {
        class = "^(clock)$",
        title = "^(clock)$",
    },
    float = true,
    size = "(monitor_w*0.33) (monitor_h*0.27)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(galculator)$",
        title = "^(galculator)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*(Calculator).*",
        title = "^(Calculator)$",
    },
    float = true,
    size = "360 620",
    center = true,
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal[^ ]*)$",
        title = "^.*([Oo]pen).*$",
    },
    float = true,
    size = "(monitor_w*0.6) (monitor_h*0.5)",
    center = true,
})

hl.window_rule({
    match = {
        class = "^([Gg]romit-mpx)$",
    },
    workspace = "special:draw",
    suppress_event = "fullscreen",
    no_shadow = true,
    border_size = 0,
    no_anim = true,
    no_blur = true,
    no_dim = true,
    float = true,
})

hl.window_rule({
    match = {
        class = "^(flameshot)$",
    },
    workspace = "special:screenshot",
    suppress_event = "fullscreen",
    stay_focused = true,
    no_shadow = true,
    border_size = 0,
    no_anim = true,
    no_blur = true,
    no_dim = true,
    float = true,
    move = "(0) (0)",
    pin = true,
})

hl.window_rule({
    match = {
        class = "^(.*[Pp]apers)$",
    },
    suppress_event = "fullscreen",
})

hl.window_rule({
    match = {
        class = "^(Godot)$",
    },
    float = false,
})

-- Source: ~/.config/hypr/hyprland-input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-input")

-- Source: ~/.config/hypr/hyprland-autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-autostart")

hl.config({
    misc = {
        -- Battery optimisation: enable vfr (variable refresh rate)
        vrr = 3,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        on_focus_under_fullscreen = 2,
        enable_anr_dialog = false, -- Disabe "App not responding" prompts
    },
    --   ######################
    --  ### Window layouts ###
    -- ######################
    general = {
        layout = "dwindle",
        --layout = master
    },
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        preserve_split = true,
        --no_gaps_when_only = 1
    },
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        -- new_is_master = true
        new_on_top = true, -- New window in stack view if true else new window focused on left
        mfact = 0.5,
    },
    --   ##########################################################################
    --  ###    HW/Device specific rules (window rules)                         ###
    -- ##########################################################################
    -- See https://wiki.hyprland.org/Configuring/Variables/#input
    --
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
    --device:epic mouse V1 {
    --  sensitivity = -0.5
    --}
    -- Wired Keyboard
    --device {
    --  name       = keyboard
    --  kb_model   =
    --  kb_layout  = de,us
    --  kb_variant =
    --  kb_options = grp:caps_toggle,fkeys:basic_13-24
    --  kb_rules   =
    --  kb_file    =
    --}
    --   ###########################################################################
    --  ###    Application specific rules (window rules)                        ###
    -- ##########################################################################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/
    -- Setup firefox, chrome Picture-in-Picture media
    -- Setup quickgui
    -- Setup keepassxc
    --windowrule = float on, center on, size (monitor_w*0.667) (monitor_h*0.667), no_screen_share on, match:class ^((org.keepassxc.)?KeePassXC)$
    -- Setup showmethekeys overlay
    -- Setup livecaptions overlay
    -- floating window rules
    -- specific window centering
    -- system update (waybar termnal)
    -- waydroid
    -- ttyclock
    -- calculator
    -- XDG File-selector
    -- gromit-mpx
    -- Note: Also enable shortcuts otherwise usage will be difficult
    -- Flameshot
    --windowrule = monitor $lMon, match:class ^(flameshot)$ # Screenshot all monitors
    -- Papers
    -- Godot
    -- nwg-drawer
    --windowrulev2 = noanim, class:^(nwg-drawer)$
    --   ##########################################################################
    --  ###    Keybindings, etc.                                               ###
    -- ##########################################################################
    -- See https://wiki.hypr.land/Configuring/Binds
    --   ##########################################################################
    --  ###    Startup rules, etc.                                             ###
    -- ##########################################################################
    -- See https://wiki.hyprland.org/Configuring/Keywords
})

hl.on("hyprland.start", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
end)

