--   ##########################################################################
--  ###    Themes, etc.                                                    ###
-- ##########################################################################

--   ####################################
--  ### Variables, Definitions, etc. ###
-- ####################################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland-var.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-var")

--   ##############################################
--  ### Catppuchin Mocha Theme by @catppuccino ###
-- ##############################################
-- @Style Guide: https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md
--                rgb(rrggbb)

-- redish
local cat_yellow = "rgb(f9e2af)"
local cat_peach = "rgb(fab387)"
--red tone
local cat_red = "rgb(f38ba8)"
local cat_maroon = "rgb(eba0ac)"
local cat_flamingo = "rgb(f2cdcd)"
local cat_rosewater = "rgb(f5e0dc)"
local cat_pink = "rgb(f5c2e7)"
-- blue tone
local cat_mauve = "rgb(cba6f7)"
local cat_blue = "rgb(89b4fa)"
local cat_lavender = "rgb(b4befe)"
local cat_sky = "rgb(89dceb)"
local cat_sapphire = "rgb(74c7ec)"
local cat_teal = "rgb(94e2d5)"
-- green tone
local cat_green = "rgb(a6e3a1)"
-- white -> black
local cat_text = "rgb(cdd6f4)"
local cat_subtext1 = "rgb(bac2de)"
local cat_subtext0 = "rgb(a6adc8)"
local cat_overlay2 = "rgb(9399b2)"
local cat_overlay1 = "rgb(7f849c)"
local cat_overlay0 = "rgb(6c7086)"
local cat_surface2 = "rgb(585b70)"
local cat_surface1 = "rgb(45475a)"
local cat_surface0 = "rgb(313244)"
local cat_base = "rgb(1e1e2e)"
local cat_mantle = "rgb(181825)"
local cat_crust = "rgb(11111b)"

--   ###########################################
--  ### Rose-Pine Theme by @jishnurajendran ###
-- ###########################################
-- @Style Guide: https://rosepinetheme.com/palette/
local rose_base = 0xff191724
local rose_surface = 0xff1f1d2e
local rose_overlay = 0xff26233a
local rose_muted = 0xff6e6a86
local rose_subtle = 0xff908caa
local rose_text = 0xffe0def4 -- light purple
local rose_love = 0xffeb6f92 -- dark pink
local rose_gold = 0xfff6c177 -- yellow
local rose_rose = 0xffebbcba -- light pink
local rose_pine = 0xff31748f -- ocean blue
local rose_foam = 0xff9ccfd8 -- red
local rose_iris = 0xffc4a7e7 -- dark purple
local rose_highlightLow = 0xff21202e
local rose_highlightMed = 0xff403d52
local rose_highlightHigh = 0xff524f67

--   ##########################################################################
--  ###    Active Theme                                                    ###
-- ##########################################################################
-- @Theme: Catppuchin
-- @Pallet: Mocha
-- @Version: 30-Sep-2023

-- Color Theme

-- Icon Theme

-- Cursor
--env = HYPRCURSOR_THEME, cur_bibata-modern-ice
--env = XCURSOR_THEME   , cur_bibata-modern-ice
--env = XCURSOR_SIZE    , 24
--env = HYPRCURSOR_SIZE , 24

hl.window_rule({
    name = "windowrule-1",
    match = {
        float = 0,
    },
  --border_color = cat_sky .. ' ' .. cat_crust .. ' ' .. cat_crust .. ' ' .. cat_sky .. " 45deg",
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        float = 1,
    },
  --border_color = cat_maroon .. ' ' .. cat_crust .. ' ' .. cat_crust  .. ' ' .. cat_maroon .. " 45deg",
})

hl.window_rule({
    name = "purple-border",
    match = {
        pin = 1,
    },
  --border_color = cat_red .. ' ' .. cat_crust .. ' ' .. cat_crust .. ' ' .. cat_red .. " 45deg",
})

hl.window_rule({
    name = "gold-border",
    match = {
        fullscreen = 1,
    },
  --border_color = cat_flamingo .. ' ' .. cat_crust .. ' ' .. cat_crust .. ' ' .. cat_flamingo .. " 45deg",
})

hl.window_rule({
    name = "red-border",
    match = {
        fullscreen_state_internal = 0,
        fullscreen_state_client = 2,
    },
  --border_color = cat_rosewater .. ' ' .. cat_crust .. ' ' .. cat_crust .. ' ' .. cat_rosewater .. " 45deg",
    --only = on
})

hl.window_rule({
    name = "salamon-border",
    match = {
        xwayland = 1,
    },
  --border_color = cat_mauve .. ' ' .. cat_crust .. ' ' .. cat_crust .. ' ' .. cat_mauve .. " 45deg",
})

hl.window_rule({
    name = "blue-border",
    match = {
        workspace = "special",
    },
  --border_color = cat_lavender .. ' ' .. cat_crust .. ' ' .. cat_crust .. ' ' .. cat_lavender .. " 45deg",
})

hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 100,
    bezier = "linear",
    style = "loop",
})

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "default",
})

hl.config({
    cursor = {
        sync_gsettings_theme = true,
        inactive_timeout = 5,
        hotspot_padding = 1,
        zoom_factor = 1.0,
        zoom_rigid = true,
        enable_hyprcursor = true,
        hide_on_key_press = false,
    },
    -- Wallpaper (now done in hyprpaper)
    --exec-once = mpvpaper '*' '~/.config/hypr/bg/smoke.mp4' -f -s -o 'mute=yes --panscan=1.0 --loop-playlist shuffle'
    --   #############################
    --  # Hyprland (window) theming #
    -- #############################
    -- Custom window borders (processed bottom to top)
    -- Window stack (bar) theme
    group = {
      --col = {
          --border_active = cat_teal .. " " .. cat_crust .. " " .. cat_crust .. " " .. cat_teal .. " 45deg",
          --border_inactive = cat_overlay0 .. " " .. cat_crust .. " " .. cat_crust .. " " .. cat_overlay0 .. " 45deg",
      --},
        groupbar = {
            text_color = cat_text,
            col = {
                active = cat_base,
                inactive = cat_crust,
            },
        },
    },
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/#general
        allow_tearing = false,
        -- Window Border
        gaps_in = 2,
        gaps_out = 2,
        border_size = 2,
        --Animated window border
        -- see: https://wiki.hypr.land/Configuring/Animations/#animation-tree
        col = {
            --active_border = cat_sky .. " " .. cat_crust .. " " .. cat_crust .. " " .. cat_sky .. " 45deg",
            --inactive_border = cat_overlay0 .. " " .. cat_crust .. " " .. cat_crust .. " " .. cat_overlay0 .. " 45deg",
        },
        layout = "dwindle", -- or master
    },
    misc = {
        font_family = "JetBrainsMono Nerd Font Mono",
        splash_font_family = "JetBrainsMono Nerd Font Mono",
    },
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/#decoration
        rounding = 2,
        dim_inactive = true,
        dim_strength = 0.1,
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,
        blur = {
            -- See https://wiki.hyprland.org/Configuring/Variables/#blur
            enabled = true,
            size = 2,
            passes = 2,
            new_optimizations = true,
            contrast = 0.8,
            brightness = 0.8,
        },
    },
    -- General window opacity
    --windowrulev2 = opacity 0.965 override 0.95 override 1 override,class:.*
    --windowrulev2 = opacity 1, fullscreenstate:0 2, class:.*
    animations = {
        -- See https://wiki.hyprland.org/Configuring/Animations/
        enabled = true,
    },
    -- ######################
    -- # Custom App configs #
    -- ######################
})

hl.on("hyprland.start", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'gtk_catppuccin-mocha-maroon'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Dracula'")
    hl.exec_cmd("exec-once = hyprctl setcursor cur_bibata-modern-ice 24")
end)

