--   ##########################################################################
--  ###    Monitors, Displays, etc.                                        ###
-- ##########################################################################
-- Configure your Display resolution, offset, scale and Monitors here
--  - Use `hyprctl monitors` to get the info.

--   ####################################
--  ### Variables, Definitions, etc. ###
-- ####################################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/hyprland-var.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("hyprland-var")

--   #################
--  ### Rendering ###
-- #################
-- See https://wiki.hyprland.org/Configuring/Monitors/

-- Prevent wayland scaling issues

hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprlock"), { locked = true })

local dp_abs_offset = 420 -- 420 ~ ( max_H - min_H )
local dp_h_scale = 1.2 -- 1.2 ~ $dp_abs_scale * ( $monitor_max_scale / $monitor_min_scale )
local dp_h_offset = 275 -- 240 ~ ( 1 / $dp_hp_scale) * $dp_abs_offset

local lMon = "HDMI-A-2" -- $(hyprctl monitors -j | jq -r 'min_by(.x).name')
local mMon = "eDP-1"
local rMon = "DP-4" -- $(hyprctl monitors -j | jq -r 'max_by(.x).name')
local vMon = "VNC"

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto-left",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

hl.monitor({
    output = "$vMon",
    mode = "1280x720@30",
    position = "auto-up",
    scale = "1",
    transform = 0,
    vrr = 1,
})

hl.monitor({
    output = "$mMon",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

hl.workspace_rule({
    workspace = "1",
    monitor = mMon,
    default = true,
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60",
    position = "0x-1080",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60",
    position = "auto-left",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

hl.monitor({
    output = "DP-4",
    mode = "1920x1080@60",
    position = "1920x0",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

hl.monitor({
    output = "DP-5",
    mode = "1920x1080@60",
    position = "3840x0",
    scale = "1",
    transform = 0,
    vrr = 1,
    cm = "auto",
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
        create_abstract_socket = true,
    },
    render = {
        direct_scanout = 2,
        cm_auto_hdr = 1,
        new_render_scheduling = true,
    },
    -- Screen sharing options
    -- File: ~/.config/hypr/xdph.conf
    -- See https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland
    -- Enable auto-rotation (requires iio-hyprland)
    -- Laptop lid close trigger
    -- On lid close
    --bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
    -- On lid open
    --bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, 1920x1080, 0x0, 1"
    --   #######################
    --  # Multi-Monitor Setup #
    -- #######################
    -- NOTE: Adding ```bitdepth , 10``` to ```monitor = ...``` breaks obs screen-capture
    -- Multi monitor scaling calculation
    -- Primary monitor (xwayland compatability)
    -- Cursor on Main Monitor (session start)
    -- Window on Main Monitor (new)
    -- Default monitor
    -- Virtual monitor (VNC)
    -- Main Monitor
    -- Left Monitor
    --monitor     = $lMon               , 1920x1080@60   , auto-left  , 1 , transform, 0, vrr, 1
    -- Right Monitor
    --monitor     = $rMon               , 1920x1080@60   , auto-right  , 1 , transform, 0, vrr, 1
    --### CUSTOM CONFIG (Docks etc.)
})

hl.on("hyprland.start", function()
    hl.exec_cmd("iio-hyprland")
    hl.exec_cmd("xrandr --output " .. mMon .. " --primary")
    hl.exec_cmd("hyprctl dispatch focusmonitor " .. mMon)
    hl.exec_cmd("xrandr --output " .. mMon .. " --primary")
end)

