#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# See: https://www.gnu.org/software/grub/manual/grub/grub.html#menuentry

menuentry "UBCD (memdisk)" --class memtest86+ --hotkey 'u' {
  # ISO: '/boot/ubcd.iso'
  # ``` sudo chmod +rx '/boot/ubcd.iso' ```
  echo "System reboot to UBCD..."
  linux16   /boot/memdisk iso bigraw
  initrd16  /boot/ubcd.iso
}

if [ ${grub_platform} == "efi" ]; then
    menuentry "UEFI Firmware" --class firmware --hotkey 'f' {
        fwsetup
    }
fi

menuentry "Restart" --class restart --hotkey 'r' {
	echo "System rebooting..."
	reboot
}

menuentry "Shutdown" --class shutdown --hotkey 'q' {
	echo "System shutting down..."
	halt
}
